### ISSUE TITLE
0.3.0 移除污染检测模块后ipset的意义？

### ISSUE THREAD

**Issue by rampageX** [wolf-joe/ts-dns#1]
如果只是 GFWList 则开始就可以完全加载，这样动态添加除了省点内存貌似就没什么意义了？

**Comment by wolf-joe** [comment]
ipset和gfwlist是独立的，我添加ipset功能的目的是想让透明网关只代理gfwlist相关的流量。

**Comment by wolf-joe** [comment]
换句话说，ts-dns只是将域名解析出来ip扔到ipset里，其它的啥也没干

**Comment by rampageX** [comment]
现在一般都是 GFWList 转成域名直接扔给 dnsmasq 处理。

BTW: 0.4.0 处理这个列表还是有点问题，范例： icloud.cdn-apple.com

这个被抓到 GFWList 去了，实际上不是。

逻辑上其实还是感觉 clean 组解析出来是国内 IP 的结果优先，GFWList 靠后，这样比较靠谱。

**Comment by wolf-joe** [comment]
基于一些个人的偏见，我不太喜欢用dnsmasq，我现在用ts-dns也是不搭配其它本地dns软件的。
至于`icloud.cdn-apple.com`域名被抓取，最新的gfwlist第2511、2512行有如下规则：
```text
.cdn-apple.com
||cdn-apple.com
```
能匹配上应该属于合理的吧😀

**Comment by rampageX** [comment]
应该说，纯依靠这个列表有问题 >_<

**Comment by wolf-joe** [comment]
嗯，确实是这样，目前只能靠规则将`cdn-apple.com`拉到clean组来缓解了。
话说国内ip+gfwlist来匹配，是不是就不会有误判的情况了？

**Comment by wolf-joe** [comment]
先假设域名为`clean`组，得到结果ip后如发现ip不属于国内、且该域名被gfwlist匹配，则认定该域名为`dirty`组。应该是这样吧~我去试试看

**Comment by rampageX** [comment]
主线的版本我编译试了下，已经没什么大问题了。

建议在 ts-dns-full.toml 范例中去掉 ` rules = ["google.com"]`，否则 dl.google.com 又被解析到国外去了，而且去掉这个并不会造成多余的错误。当然也可以提高命中 cnip 的优先级来处理这个问题。

作为 XX 用其实已经差不多了，小建议：
1. 增加 bootrap dns 来处理 tls-dns, https-tls 的域名解析问题；（例如非标端口的 DNS 服务器）
2. 增加 fallback dns 处理上游服务器全部失效的情况。

**Comment by wolf-joe** [comment]
我个人还是`cnip`这种隐式匹配的优先级还是不能高于`rules`这种显式配置的优先级的。
主要还是因为google.com在gfwlist.txt里是以一个正则的形式存在的，我偷懒没有做兼容，这就导致如果不靠`rules`打补丁的话google.com就分不到`dirty`组去。争取在下个版本解决对这个正则的支持。

**Comment by wolf-joe** [comment]
dot、doh的域名解析和fallback dns应该可以看成一件事吧。主要还是稳定性的问题，我这用非标端口的国外dns还是有一定几率丢包。我打算加个并发请求的功能来解决这个问题~
