### ISSUE TITLE
  rules的值采用读取路径txt的内容

### ISSUE THREAD

**Issue by thb007** [wolf-joe/ts-dns#10]
如默认为  rules = ["company.com"]
改为  rules = "./xx.txt"
xx.txt里面的内容格式为
Baidu.com
qq.com
youku.com
www.google.com
......
这样好处就是减少配置文件的大小，方便编辑，看起来也没那么乱。

**Comment by wolf-joe** [comment]
感谢建议，会在下个版本添加

**Comment by wolf-joe** [comment]
[v0.12.0](https://github.com/wolf-joe/ts-dns/releases/tag/v0.12.0)发布，支持从文件中读取group的匹配规则
