### ISSUE TITLE
gfwlist.txt的配置有问题

### ISSUE THREAD

**Issue by weargle** [wolf-joe/ts-dns#11]
在最新版中提供了gfwlist.txt是否要base64解码，我将gfwlist.txt文件先使用base64解码后，在配置文件里面配置gfwlist_b64 = false，但是拿gfwlist.txt里面的域名使用dig测试发现没有匹配上，如果设置为需要解码正常匹配上。

配置文件图
![image](https://user-images.githubusercontent.com/26951765/79678593-c47fb900-822f-11ea-8bde-64af548cef92.png)

gfwlist.txt文件图
![image](https://user-images.githubusercontent.com/26951765/79678602-d9f4e300-822f-11ea-8905-fac520e74e1e.png)

测试图
![image](https://user-images.githubusercontent.com/26951765/79678654-496ad280-8230-11ea-9d75-da64d3f9667e.png)

gfwlist.txt设置解码的测试图
![image](https://user-images.githubusercontent.com/26951765/79678887-9fd91080-8232-11ea-810a-0c49aa49d630.png)

**Comment by wolf-joe** [comment]
已在commit：https://github.com/wolf-joe/ts-dns/commit/cba213810ae27d1a6b6117251852619fc3fa8be2 中修复，预计在未来几天发布release

**Comment by wolf-joe** [comment]
[v0.12.0](https://github.com/wolf-joe/ts-dns/releases/tag/v0.12.0)发布，修复gfwlist文件换行符bug
