### ISSUE TITLE
"fastest_v4 = true"功能是不是有bug

### ISSUE THREAD

**Issue by 36bian** [wolf-joe/ts-dns#15]
我是把软件专门放在一个机器上做网关用的，自己PC访问。
部署中发现，"fastest_v4 = true"之后所有网页都打不开，注释以后正常。不知道是不是个例

还有个疑问就是，如果返回的某国外IP不在gfw名单里，是走直连还是代理？prdns那个判断是否被墙的思想挺先进的，希望我们也能做成那样，智能判断黑名单

**Comment by wolf-joe** [comment]
* bug相关issue请给出ts-dns运行日志和配置文件。
* ts-dns只负责域名解析，所以我不明白你指的`IP……是走直连还是代理`是什么意思。
* ts-dns在早期版本(`<=v0.2`)内置了类似prdns的污染检测机制，但实际用下来后发现误判率比较高，包括`"google.com", "twimg.com", "quoracdn.net"`等被污染的域名无法正确识别，一些没有被污染的域名反而会识别为被污染。

**Comment by 36bian** [comment]
ts-dns.toml
```shell
listen = ":53"
gfwlist = "gfwlist.txt"
cnip = "cnip.txt"

[groups]
  [groups.clean]
  dns = ["223.5.5.5","223.6.6.6"]
  concurrent = true
  fastest_v4 = true # 把这注了就好了
  [groups.dirty]
  dns = ["127.0.0.1:5353/tcp"] 
```

debug output
```shell
~/ts-dns # ./ts-dns -vv
DEBU[0000] show debug log
WARN[0000] enable concurrent dns in group clean
WARN[0000] find fastest ipv4 in group clean
DEBU[0000] ecs conf: <nil>
DEBU[0000] ecs conf: <nil>
WARN[0000] listen on :53/udp
DEBU[0003] question: [{qq.com. 1 1}], extract: []
DEBU[0003] forward question [{qq.com. 1 1}] to &{0xc0000f9500 223.5.5.5:53 <nil> 0xc0002feff0}
DEBU[0003] forward question [{qq.com. 1 1}] to &{0xc0000f9570 223.6.6.6:53 <nil> 0xc0002ff050}
ERRO[0005] query dns error: read udp 192.168.6.2:37951->223.6.6.6:53: i/o timeout
INFO[0005] cn/empty ipv4                                 domain=qq.com. group=clean src=192.168.6.189 type=A
DEBU[0005] question: [{www.qq.com. 1 1}], extract: []
DEBU[0005] forward question [{www.qq.com. 1 1}] to &{0xc0000f9500 223.5.5.5:53 <nil> 0xc0002feff0}
DEBU[0005] forward question [{www.qq.com. 1 1}] to &{0xc0000f9570 223.6.6.6:53 <nil> 0xc0002ff050}
ERRO[0007] query dns error: read udp 192.168.6.2:55066->223.6.6.6:53: i/o timeout
INFO[0007] cn/empty ipv4                                 domain=www.qq.com. group=clean src=192.168.6.189 type=A
DEBU[0007] question: [{www.qq.com. 1 1}], extract: []
INFO[0007] hit cache                                     domain=www.qq.com. src=192.168.6.189 type=A
DEBU[0007] question: [{google.com. 1 1}], extract: []
DEBU[0007] forward question [{google.com. 1 1}] to &{0xc0000f9500 223.5.5.5:53 <nil> 0xc0002feff0}
DEBU[0007] forward question [{google.com. 1 1}] to &{0xc0000f9570 223.6.6.6:53 <nil> 0xc0002ff050}
DEBU[0007] question: [{www.qq.com. 1 1}], extract: []
INFO[0007] hit cache                                     domain=www.qq.com. src=192.168.6.189 type=A
ERRO[0009] query dns error: read udp 192.168.6.2:51270->223.5.5.5:53: i/o timeout
ERRO[0009] find fastest ipv4 failed
```

**Comment by wolf-joe** [comment]
抱歉，ts-dns的debug日志还不完善。但日志里并未出现异常，同样的配置在我的网络环境下也能正常工作。如果可以的话，请使用dig工具检测ts-dns，或是等下一个有更多debug日志的版本发布后再反馈此问题。

**Comment by 36bian** [comment]
dig 命令
```shell
dig +short @192.168.6.2 baidu.com
>>> 39.156.69.79
```
debug output
```shell
~/ts-dns # ./ts-dns -vv
DEBU[0000] show debug log
WARN[0000] enable concurrent dns in group clean
WARN[0000] find fastest ipv4 in group clean
DEBU[0000] ecs conf: <nil>
DEBU[0000] ecs conf: <nil>
WARN[0000] listen on :53/udp
DEBU[0007] question: [{baidu.com. 1 1}], extract: [
;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: ; udp: 4096]
INFO[0007] match by rules                                domain=baidu.com. group=clean src=192.168.6.189 type=A
DEBU[0007] forward question [{baidu.com. 1 1}] to &{0xc0000f8380 223.5.5.5:53 <nil> 0xc000325230}
DEBU[0007] forward question [{baidu.com. 1 1}] to &{0xc0000f83f0 223.6.6.6:53 <nil> 0xc000325290}
```
奇怪的是dig和curl都能工作，只有浏览器不行，所有网页都打不开
❗️**无法访问此网站找不到 www.baidu.com 的服务器 IP 地址。DNS_PROBE_FINISHED_NXDOMAIN**
```shell
curl baidu.com
>>> <html>
>>> <meta http-equiv="refresh" content="0;url=http://www.baidu.com/">
>>> </html>
```

**Comment by 36bian** [comment]
OK 也许只是个例，好在不启用也能正常工作，接下来就看下日常工作稳定性了

**Comment by weargle** [comment]
你试下获取百度的ip使用ping工具ping下有没有结果返回，有些机器禁ping的话这个设置就出现问题，因为这个设置按照作者说法是在返回结果ip中找出耗时最短的ip

**Comment by 36bian** [comment]
@weargle 我在网关机器上是可以ping的，所以这个问题很奇怪。

**Comment by wolf-joe** [comment]
> 你试下获取百度的ip使用ping工具ping下有没有结果返回，有些机器禁ping的话这个设置就出现问题，因为这个设置按照作者说法是在返回结果ip中找出耗时最短的ip

ping的话我设了500ms的超时时间，对方禁ping的话会提示“find fastest ipv4 failed”，但还是能正常返回查询结果的

**Comment by 36bian** [comment]
@wolf-joe 不过我想谈谈另一个问题，我在全部流量不做区分直接导入代理，载入github.com 5.7s，用了ipset-blocked区分黑名单才代理，结果载入花了20多s，这也太惨了点
![image](https://user-images.githubusercontent.com/32314569/80115505-63e9d680-85b7-11ea-999c-cf2529b1c948.png)

**Comment by wolf-joe** [comment]
> @wolf-joe 不过我想谈谈另一个问题，我在全部流量不做区分直接导入代理，载入github.com 5.7s，用了ipset-blocked区分黑名单才代理，结果载入花了20多s，这也太惨了点
> ![image](https://user-images.githubusercontent.com/32314569/80115505-63e9d680-85b7-11ea-999c-cf2529b1c948.png)
> 如果黑名单能够更加智能的话，比如不仅是被污染、而且能识别用哪个渠道更快，就太好了

我觉得你可能对dns服务有很大的误解……如果你的宽带直连海外ip速度不行的话，可以在透明代理网关处设置“非国区IP走代理”，这方面的教程还是挺多的。

**Comment by weargle** [comment]
> > @ wolf-joe不过我想谈谈另一个问题，我在全部流量不做分开直接导入代理，加载github.com 5.7s，用了ipset-blocked区分黑名单才代理，结果载入花了20多s，这也太惨了点
> > 如果黑名单能够更加智能的话，只是另外是被污染，而且能识别用其中渠道置换，就太好了
> > ![图片](https://user-images.githubusercontent.com/32314569/80115505-63e9d680-85b7-11ea-999c-cf2529b1c948.png)
> 
> 我觉得你可能对dns服务有很大的误解……如果你的宽带直连海外ip速度不行的话，可以在透明代理网关处所设置“非国区IP走代理”，这方面的教程还是挺多的。
> 顺便一提，如果是脏组域名加入了blockedipset，且blockedipip代理的话，`github.com`这个域名是会走代理的，我一直在用这个方案。`github.githubassets.com`等静态资源的域名虽然不会走代理，但只要不减少预算缓存，静态资源加载慢点就不会对日常浏览造成什么影响。

麻烦问下你有没有使用过反代，我使用v2做反代发现有些图片没法加载，chrone浏览器里面扩展的图片没有加载，图标这类倒是加载成功，我不清楚是什么情况，这个你有没有解决办法。

**Comment by 36bian** [comment]
@weargle 不是对DNS有误解，是对咱们软件要求太高了😶

**Comment by weargle** [comment]
> @weargle不是对DNS有误解，是对咱们软件要求太高了

我对github的处理方案是，github.com走国内dns,githubusercontent.com走国外dns，github.com没有多少污染。想要智能八成需要加入智能学习，之前有个dns是加入但作者不更新了，我不敢用，而且看了issu感觉问题还不少

**Comment by wolf-joe** [comment]
> > > @ wolf-joe不过我想谈谈另一个问题，我在全部流量不做分开直接导入代理，加载github.com 5.7s，用了ipset-blocked区分黑名单才代理，结果载入花了20多s，这也太惨了点
> > > 如果黑名单能够更加智能的话，只是另外是被污染，而且能识别用其中渠道置换，就太好了
> > > ![图片](https://user-images.githubusercontent.com/32314569/80115505-63e9d680-85b7-11ea-999c-cf2529b1c948.png)
> > 
> > 
> > 我觉得你可能对dns服务有很大的误解……如果你的宽带直连海外ip速度不行的话，可以在透明代理网关处所设置“非国区IP走代理”，这方面的教程还是挺多的。
> > 顺便一提，如果是脏组域名加入了blockedipset，且blockedipip代理的话，`github.com`这个域名是会走代理的，我一直在用这个方案。`github.githubassets.com`等静态资源的域名虽然不会走代理，但只要不减少预算缓存，静态资源加载慢点就不会对日常浏览造成什么影响。
> 
> 麻烦问下你有没有使用过反代，我使用v2做反代发现有些图片没法加载，chrone浏览器里面扩展的图片没有加载，图标这类倒是加载成功，我不清楚是什么情况，这个你有没有解决办法。

既没用过v2也没用过反代😂

**Comment by wolf-joe** [comment]
> @weargle 不是对DNS有误解，是对咱们软件要求太高了😶

不是要求高不高的问题。这个feat说起来也简单，就是定时检测某网站直连/代理的访问速度，比较速度后决定将这个网站的ip从ipset移除/添加到ipset。但这个feat放到dns层面来做就很诡异了，因为这事和dns八竿子打不着。

**Comment by weargle** [comment]
> > > > @ wolf-joe不过我想谈谈另一个问题，我在全部流量不做分开直接导入代理，加载github.com 5.7s，用了ipset-blocked区分黑名单才代理，结果载入花了20多s ，这也太惨了点
> > > > 如果黑名单能够更加智能的话，只是另外是被污染，而且能识别用其中渠道替换，就太好了
> > > > ![图片](https://user-images.githubusercontent.com/32314569/80115505-63e9d680-85b7-11ea-999c-cf2529b1c948.png)
> > > 
> > > 
> > > 我觉得你可能对dns服务有很大的误解……如果你的宽带直连海外ip速度不行的话，可以在透明代理网关处所设置“非国区IP走代理”，这方面的教程还是挺多的。
> > > 顺便一提，如果是脏组域名加入了blockedipset，且blockedipip代理的话，`github.com`这个域名是会走代理的，我一直在用这个方案。`github.githubassets.com`等静态资源的域名虽然不会走代理，但只要不减少预算缓存，静态资源加载慢点就不会对日常浏览造成什么影响。
> > 
> > 
> > 麻烦问下你有没有使用过反代，我使用v2做反代发现有些图片没法加载，chrone浏览器里面扩展的图片没有加载，图标某种倒是加载成功，我看不到是什么情况，这个你有没有解决办法。
> 
> 既没用过v2也没用过反代

明白。0.12你adblock规则匹配了哪些匹配符，我拿广告域名试试

**Comment by wolf-joe** [comment]
> > > > > @ wolf-joe不过我想谈谈另一个问题，我在全部流量不做分开直接导入代理，加载github.com 5.7s，用了ipset-blocked区分黑名单才代理，结果载入花了20多s ，这也太惨了点
> > > > > 如果黑名单能够更加智能的话，只是另外是被污染，而且能识别用其中渠道替换，就太好了
> > > > > ![图片](https://user-images.githubusercontent.com/32314569/80115505-63e9d680-85b7-11ea-999c-cf2529b1c948.png)
> > > > 
> > > > 
> > > > 我觉得你可能对dns服务有很大的误解……如果你的宽带直连海外ip速度不行的话，可以在透明代理网关处所设置“非国区IP走代理”，这方面的教程还是挺多的。
> > > > 顺便一提，如果是脏组域名加入了blockedipset，且blockedipip代理的话，`github.com`这个域名是会走代理的，我一直在用这个方案。`github.githubassets.com`等静态资源的域名虽然不会走代理，但只要不减少预算缓存，静态资源加载慢点就不会对日常浏览造成什么影响。
> > > 
> > > 
> > > 麻烦问下你有没有使用过反代，我使用v2做反代发现有些图片没法加载，chrone浏览器里面扩展的图片没有加载，图标某种倒是加载成功，我看不到是什么情况，这个你有没有解决办法。
> > 
> > 
> > 既没用过v2也没用过反代
> 
> 明白。0.12你adblock规则匹配了哪些匹配符，我拿广告域名试试

v0.12.0对gfwlist.txt里的内容都是匹配的，还匹配*号通配符
https://github.com/wolf-joe/ts-dns/blob/v0.12.0/matcher/adblock_test.go
