### ISSUE TITLE
能否解释下min_ttl、max_ttl含义

### ISSUE THREAD

**Issue by 36bian** [wolf-joe/ts-dns#16]
摘自配置文件
```shell
[cache]  # dns缓存配置
size = 4096  # 缓存大小，为负数时禁用缓存
min_ttl = 60  # 最小ttl，单位为秒
max_ttl = 86400  # 最大ttl，单位为秒
```
我不太理解最小和最大是怎么回事，不应该是一个固定值么，表示ts-dns本身将会缓存该解析多长时间

**Comment by wolf-joe** [comment]
对权威DNS服务器来说，记录的TTL是固定的，代表这个记录可以被缓存的时间。对于递归DNS服务器或缓存服务器（比如ts-dns）来说，这个值是动态的，代表这个记录的缓存多久失效、需要重新向权威服务器查询。

**Comment by 36bian** [comment]
我不明白的就是这点，如果是动态的话，过期时间到底是看min_ttl还是max_ttl

**Comment by wolf-joe** [comment]
抱歉，没解释清楚。
即使上游dns告诉ts-dns：“你查到的dns记录马上就要过期了”，ts-dns也会在`min_ttl`秒后才会再次向上游dns请求相同的记录；
即使上游dns告诉ts-dns：“你查到的dns永远不会过期”，ts-dns也会在`max_ttl`秒后就再次向上游dns请求相同的记录。
总而言之，`min_ttl`和`max_ttl`存在的意义就是保证ts-dns里dns记录被缓存的时间不至于太长或太短。
