### ISSUE TITLE
rules文件没有匹配adblock规则

### ISSUE THREAD

**Issue by weargle** [wolf-joe/ts-dns#17]
试了你说的自定义广告组，发现只有rules支持，rules文件不支持。adblock规则只支持@@和||匹配符。希望能匹配rules文件，不然你说的这个没有多大用处，那么大的广告域名写在配置文件里不利于修改配置文件。

**Comment by wolf-joe** [comment]
ts-dns的`rules`配置项、`rules_file`配置项、`gfwlist`配置项用的都是同一套匹配规则，应该不会出现`rules`支持但`rules_file`不支持的情况，我的测试结果也是这样的。
至于这个匹配规则的兼容性，目前确实还只保证支持[gfwlist/gfwlist](https://github.com/gfwlist/gfwlist/blob/master/gfwlist.txt)里的规则，有其它规则的兼容需要可以提issue。

**Comment by weargle** [comment]
> TS-DNS的`rules`配置项，`rules_file`配置项，`gfwlist`配置项用的都是同一套匹配规则，不会应该出现`rules`请立即获取iTunes但`rules_file`不请立即获取iTunes的情况，我的测试结果也是这样的。
> 至于这个匹配规则的兼容性，目前确实还只保证支持[gfwlist / gfwlist](https://github.com/gfwlist/gfwlist/blob/master/gfwlist.txt)里的规则，有其他规则的兼容需要可以提签。

再测试了一次发现是正确的，可能上次测试弄错了什么。其他暂时也不知道提什么，因为你已经匹配了*，没有匹配符的域名也匹配了，其他也没有什么了，毕竟这是dns不是浏览器，需要匹配adblock全部规则。
如果暂时不知道更新什么，可以添加返回的dns服务名称，当时使用smartdns看到这个功能很惊艳，搞的像个提供公共服务的dns，返回dns服务名称，这个功能其实可有可无的，你认为不用就不要在意这个我说的。

**Comment by weargle** [comment]
规则匹配错误了！！！ #imap.163.com、p.163.com 这个域名在广告域名文件中没有找到，但发现这个域名被匹配到了，请教下 #. 你是当做 #. 还是当做匹配任何单字符

**Comment by wolf-joe** [comment]
> 规则匹配错误了！！！`imap.163.com、p.163.com` 这个域名在广告域名文件中没有找到，但发现这个域名被匹配到了，请教下 `.` 你是当做 `.` 还是当做匹配任何单字符

`.`只会匹配`.`自生。请给出配置文件和ts-dns的日志，或是能复现的流程。

**Comment by weargle** [comment]
> > 规则匹配错误了！！！`imap.163.com、p.163.com`这个域名在广告域名文件中没有找到，但发现这个域名被匹配到了，请教下`.`你是当做`.`还是当做匹配任何单字符
> 
> `.`只能匹配`.`自生。请配置文件和ts-dns的日志，或者能复现的流程。



> > 规则匹配错误了！！！`imap.163.com、p.163.com`这个域名在广告域名文件中没有找到，但发现这个域名被匹配到了，请教下`.`你是当做`.`还是当做匹配任何单字符
> 
> `.`只能匹配`.`自生。请配置文件和ts-dns的日志，或者能复现的流程。

配置文件广告组
`[groups.blocked]
  rules_file = "rules.txt"`

ts-dns日志图
![image](https://user-images.githubusercontent.com/26951765/80727613-812f1f80-8b38-11ea-8fed-bed0b8d5b97e.png)

广告域名文件
[rules.txt](https://github.com/wolf-joe/ts-dns/files/4559222/rules.txt)

**Comment by wolf-joe** [comment]
> > > 规则匹配错误了！！！`imap.163.com、p.163.com`这个域名在广告域名文件中没有找到，但发现这个域名被匹配到了，请教下`.`你是当做`.`还是当做匹配任何单字符
> > 
> > 
> > `.`只能匹配`.`自生。请配置文件和ts-dns的日志，或者能复现的流程。
> 
> > > 规则匹配错误了！！！`imap.163.com、p.163.com`这个域名在广告域名文件中没有找到，但发现这个域名被匹配到了，请教下`.`你是当做`.`还是当做匹配任何单字符
> > 
> > 
> > `.`只能匹配`.`自生。请配置文件和ts-dns的日志，或者能复现的流程。
> 
> 配置文件广告组
> `[groups.blocked] rules_file = "rules.txt"`
> 
> ts-dns日志图
> ![image](https://user-images.githubusercontent.com/26951765/80727613-812f1f80-8b38-11ea-8fed-bed0b8d5b97e.png)
> 
> 广告域名文件
> [rules.txt](https://github.com/wolf-joe/ts-dns/files/4559222/rules.txt)

`rules.txt`第`133290`行内容：`163.com`。如果我对adblock plus的规则理解没错的话，这行规则会匹配`*.163.com`和`163.com`两类域名。

**Comment by weargle** [comment]
> > > > 规则匹配错误了！！！`imap.163.com、p.163.com`这个域名在广告域名文件中没有找到，但发现这个域名被匹配到了，请教下`.`你是当做`.`还是当做匹配任何单字符
> > > 
> > > 
> > > `.`只能匹配`.`自生。请配置文件和ts-dns的日志，或者能复现的流程。
> > 
> > 
> > > > 规则匹配错误了！！！`imap.163.com、p.163.com`这个域名在广告域名文件中没有找到，但发现这个域名被匹配到了，请教下`.`你是当做`.`还是当做匹配任何单字符
> > > 
> > > 
> > > `.`只能匹配`.`自生。请配置文件和ts-dns的日志，或者能复现的流程。
> > 
> > 
> > 配置文件广告组
> > `[groups.blocked] rules_file = "rules.txt"`
> > ts-dns日志图
> > ![image](https://user-images.githubusercontent.com/26951765/80727613-812f1f80-8b38-11ea-8fed-bed0b8d5b97e.png)
> > 广告域名文件
> > [rules.txt](https://github.com/wolf-joe/ts-dns/files/4559222/rules.txt)
> 
> `rules.txt`第`133290`行内容：`163.com`。如果我对adblock plus的规则理解没错的话，这行规则会匹配`*.163.com`和`163.com`两类域名。

翻看了adblock规则确实这样，非常抱歉，我以为这种不带匹配符的域名是完整匹配，没有想到这种在adblock规则里面。

**Comment by weargle** [comment]
不知道你有没有遇到过，github的开贴人的头像有时候显示不出来，开贴人的头像请求的域名`avatars0.githubusercontent.com` ,你把这个域名使用国内dns还是国外dns请求。
![image](https://user-images.githubusercontent.com/26951765/80779237-a1dd9080-8b9d-11ea-972f-a9b29f95587a.png)

**Comment by wolf-joe** [comment]
> 不知道你有没有遇到过，github的开贴人的头像有时候显示不出来，开贴人的头像请求的域名`avatars0.githubusercontent.com` ,你把这个域名使用国内dns还是国外dns请求。
> ![image](https://user-images.githubusercontent.com/26951765/80779237-a1dd9080-8b9d-11ea-972f-a9b29f95587a.png)

`githubusercontent.com`目前还没有加入[gfwlist/gfwlist](https://github.com/gfwlist/gfwlist)，解析不正常的话需要手动加入其它group。

**Comment by weargle** [comment]
> > 不知道你有没有遇到过，github的开贴人的头像有时候显示不出来，开贴人的头像请求的域名`avatars0.githubusercontent.com` ,你把这个域名使用国内dns还是国外dns请求。
> > ![image](https://user-images.githubusercontent.com/26951765/80779237-a1dd9080-8b9d-11ea-972f-a9b29f95587a.png)
> 
> `githubusercontent.com`目前还没有加入[gfwlist/gfwlist](https://github.com/gfwlist/gfwlist)，解析不正常的话需要手动加入其它group。

`raw.githubusercontent.com` 这个域名的请求容易被重定向，然后我就把`githubusercontent.com`整个添加gfwlist文件，好的，我明白了。
