### ISSUE TITLE
0.13.0 关于监听 udp/tcp 的问题

### ISSUE THREAD

**Issue by rampageX** [wolf-joe/ts-dns#19]
现在的逻辑是只能单独监听 udp 或者 tcp？ 因为我试过 listen 并不允许指定两次，如果不指定默认也只是监听 udp。

按照常规做法，应该是无论如何都监听 udp，而 tcp 可选，比如增加一个选项：

> listen = ":53"
> listen_tcp = true

或者不指定就默认同时监听 udp 和 tcp。

**Comment by wolf-joe** [comment]
嗯，powerdns的递归服务器就是默认同时监听udp/tcp。下个版本改成同时监听吧。

**Comment by wolf-joe** [comment]
[v0.13.1](https://github.com/wolf-joe/ts-dns/releases/tag/v0.13.1)已发布，默认同时监听TCP/UDP端口 (#19)

**Comment by weargle** [comment]
测试发现默认监听udp53端口，没有监听tcp。

dns启动图
![image](https://user-images.githubusercontent.com/26951765/81472665-35613200-922c-11ea-9406-75cd91e62fa7.png)

程序运行占用端口图
![image](https://user-images.githubusercontent.com/26951765/81472701-65a8d080-922c-11ea-8286-a3df9a84a8bd.png)
