### ISSUE TITLE
哪里有cnip.txt文件？

### ISSUE THREAD

**Issue by luckypoem** [wolf-joe/ts-dns#2]
hi。

yudeMacBook-Air:~ brite$ sudo ts-dns -c ts-dns.toml
Password:
2020/03/15 11:28:01 [CRITICAL] read cnip error: open cnip.txt: no such file or directory
yudeMacBook-Air:~ brite$

tks

**Comment by wolf-joe** [comment]
`v0.5.0`之后的release包中包含的这个文件，可以下载release包使用~
`cnip.txt`本质上是用于判断域名污染情况的CN区IP列表，比如：
```text
1.0.1.0/24
1.0.2.0/23
1.0.8.0/21
...
```
也可以通过以下shell命令自行生成：
```shell
wget -c http://ftp.apnic.net/stats/apnic/delegated-apnic-latest
cat delegated-apnic-latest | awk -F '|' '/CN/&&/ipv4/ {print $4 "/" 32-log($5)/log(2)}' > cnip.txt
```
