### ISSUE TITLE
win10下重新加载配置文件命令报错

### ISSUE THREAD

**Issue by borpubi** [wolf-joe/ts-dns#26]
操作系统WINDOWS 10 VER 2004
当已经运行一个实例后，修改配置文件，使用,\ts-dns.exe -r 后报错：
`
D:\u1008\ts-dns_run>ts-dns -r
time="2020-07-07T15:01:02+08:00" level=warning msg="enable concurrent dns in group clean"
time="2020-07-07T15:01:02+08:00" level=warning msg="auto reload ts-dns.toml"
time="2020-07-07T15:01:02+08:00" level=warning msg="listen on :53/tcp"
time="2020-07-07T15:01:02+08:00" level=warning msg="listen on :53/udp"
time="2020-07-07T15:01:02+08:00" level=error msg="listen udp :53: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."`

此时，可以看到运行了两个ts-dns.exe
![image](https://user-images.githubusercontent.com/28093885/86732533-1122a580-c063-11ea-8666-10af7fb3da4a.png)

当已经运行一个实例后，修改配置文件，使用,\ts-dns.exe -r -c ts-dns-user.toml 后报错：
`D:\u1008\ts-dns_run>ts-dns -r -c ts-dns-users.toml
time="2020-07-07T15:04:38+08:00" level=warning msg="disable ipv6 resolve"
time="2020-07-07T15:04:38+08:00" level=warning msg="enable concurrent dns in group clean"
time="2020-07-07T15:04:38+08:00" level=warning msg="find fastest ipv4 in group clean"
time="2020-07-07T15:04:38+08:00" level=warning msg="auto reload ts-dns-users.toml"
time="2020-07-07T15:04:38+08:00" level=warning msg="listen on :53/udp"
time="2020-07-07T15:04:38+08:00" level=error msg="listen udp :53: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
time="2020-07-07T15:04:38+08:00" level=info msg="ts-dns exited."`

烦请大佬告知是否哪里操作错误还是程序有BUG?
我印象中V13.0的时候，直接 .\ts-dns.exe -r就可以直接重新加载配置文件的。

**Comment by wolf-joe** [comment]
自动加载配置的意思是`ts-dns`在运行期间会监听配置文件，当配置文件被改变时会重新载入配置。整个过程不需要（也不能）手动操作。

**Comment by borpubi** [comment]
> 自动加载配置的意思是`ts-dns`在运行期间会监听配置文件，当配置文件被改变时会重新载入配置。整个过程不需要（也不能）手动操作。

也就是说：如果使用命令：.\ts-dns.exe -r -c ts-dns-user.toml 运行程序的话，如果配置文件有更新会自动加载？

**Comment by wolf-joe** [comment]
> > 自动加载配置的意思是`ts-dns`在运行期间会监听配置文件，当配置文件被改变时会重新载入配置。整个过程不需要（也不能）手动操作。
> 
> 也就是说：如果使用命令：.\ts-dns.exe -r -c ts-dns-user.toml 运行程序的话，如果配置文件有更新会自动加载？

对

**Comment by borpubi** [comment]
> > > 自动加载配置的意思是`ts-dns`在运行期间会监听配置文件，当配置文件被改变时会重新载入配置。整个过程不需要（也不能）手动操作。
> > 
> > 
> > 也就是说：如果使用命令：.\ts-dns.exe -r -c ts-dns-user.toml 运行程序的话，如果配置文件有更新会自动加载？
> 
> 对

好的，谢谢，我改一下执行命令。
