### ISSUE TITLE
How do run in the background in win10?

### ISSUE THREAD

**Issue by ZmdnaHF0ZmFqYXZ0O** [wolf-joe/ts-dns#28]
Hi，
I use a cmd.exe to run the ts-dns.exe(Not closing the cmd window) and then use a cmd.exe to do a domain lookup using nslookup, I found that it is using the local DNS, how do verify the ts-dns in win10?

win10 Version 10.0.18363
ts-dns Windows_x86_64 Version 0.14.1

**Comment by wolf-joe** [comment]
ts-dns can't run in background under win10 by itself, please consider third party process manage tool like [pm2](https://pm2.keymetrics.io/).

**Comment by wolf-joe** [comment]
you can run ts-dns.exe in one termianl and keep it running, then open another terminal to verify ts-dns use nslookup.
