### ISSUE TITLE
提个建议，希望作者能把最近新的DNS TYPE65请求屏蔽功能增加上，谢谢

### ISSUE THREAD

**Issue by fox85** [wolf-joe/ts-dns#30]
鉴于最近ios升级了14之后，会默认发出qtype 65的DNS请求，这样的话有可能令使用翻墙的我们带来了不希望的CDN解析的结果，希望大佬能采纳，谢谢！

**Comment by rampageX** [comment]
建议直接做可自定义禁止查询的类型: disable_qtype = ["AAAA", "NS", "HTTPS"]

**Comment by wolf-joe** [comment]
working on it

**Comment by wolf-joe** [comment]
已经加到最新的commit了，配置文件参考`ts-dns-full.toml`

**Comment by fox85** [comment]
> 已经加到最新的commit了，配置文件参考`ts-dns-full.toml`

非常感谢大佬的快速响应！

另外请问可否帮忙编译好一份二进制可执行文件放在release，最近的一份是5月19日的了

**Comment by wolf-joe** [comment]
[v0.15](https://github.com/wolf-joe/ts-dns/releases/tag/v0.15)已发布
