### ISSUE TITLE
Commit fc7f2cc 运行一段时间就出错退出

### ISSUE THREAD

**Issue by rampageX** [wolf-joe/ts-dns#31]
退回 6da1a6f 没问题. 日志见附件.
[ts-dns.log](https://github.com/wolf-joe/ts-dns/files/5358632/ts-dns.log)

**Comment by wolf-joe** [comment]
翻车了，抱歉😂
推了个新commit，fix掉了

**Comment by rampageX** [comment]
开多了,翻车是必然的~ 现在好啦~
