### ISSUE TITLE
可以将查询结果中的IPv6地址也添加至IPSet中吗

### ISSUE THREAD

**Issue by chinnkarahoi** [wolf-joe/ts-dns#33]

**Comment by wolf-joe** [comment]
on the way，预计下个版本上线

**Comment by wolf-joe** [comment]
> on the way，预计下个版本上线

大意了，一个ipset不能同时支持ipv4和ipv6，如果想添加的话只能单独弄个ipset……

**Comment by wolf-joe** [comment]
1146c17c395e05c7f79287545a4167211fc084b0 已支持，并发布到了v1.1.0版本
