### ISSUE TITLE
建议增加SIGHUP处理

### ISSUE THREAD

**Issue by semigodking** [wolf-joe/ts-dns#34]
使用过程中，如果发现了GFW list 不支持的域名，就会修改config文件，修改完，希望能够通过kill -SIGHUP的方式使配置重新加载。

**Comment by wolf-joe** [comment]
ts-dns可以监听配置文件，当配置文件发生变化时会自动重新加载配置文件。同时也可以使用supervisor、pm2、systemd等工具来托管运行ts-dns，执行相关命令即可重启ts-dns。

**Comment by semigodking** [comment]
这个搞起来有难度。由于这个工具并不是一个普适的工具，使用的人也少，所以暂不打算花太多精力实现这个功能。
如果有PR的话，我是很欢迎的。

OrangeWolf <notifications@github.com> 于 2021年2月9日周二 18:17写道：
