### ISSUE TITLE
fastest ipv4 报错。

### ISSUE THREAD

**Issue by hkthomas** [wolf-joe/ts-dns#36]
DEBIAN 10 X64。

root运行。

一直在报错 。
ERRO[0023] find fastest ipv4 failed。

偶尔还会有这个错误。
->223.5.5.5:53: i/o timeout  LOCATION="server.go:45" LOG_ID=3859

**Comment by wolf-joe** [comment]
信息不足，请给出更详细的日志

**Comment by hkthomas** [comment]
root@cc:~/dns/ts-dns# ./ts-dns
WARN[0000] enable concurrent dns in group clean         
WARN[0000] find fastest ipv4 in group clean             
WARN[0000] listen on :7777/udp                          
WARN[0000] listen on :7777/tcp                          
ERRO[0013] find fastest ipv4 failed                     
ERRO[0014] find fastest ipv4 failed                     
ERRO[0014] find fastest ipv4 failed                     
ERRO[0014] find fastest ipv4 failed                     
ERRO[0024] find fastest ipv4 failed                     
ERRO[0026] find fastest ipv4 failed                     
ERRO[0026] find fastest ipv4 failed                     
ERRO[0026] find fastest ipv4 failed                     
ERRO[0026] find fastest ipv4 failed                     
ERRO[0051] find fastest ipv4 failed                     
ERRO[0053] find fastest ipv4 failed 
ERRO[0053] query dns error: read udp 192.168.1.219:49326->223.5.5.5:53: i/o timeout  LOCATION="server.go:45" LOG_ID=1903 QUESTION=BING.COM. Q_TYPE=A SRC="127.0.0.1:37825"
ERRO[0053] find fastest ipv4 failed

启动就开始报这个，但是可以正常查询。

后面那个好像是查询超时了。

要帖配置上来看下吗？

**Comment by wolf-joe** [comment]
嗯，麻烦贴一下配置

**Comment by hkthomas** [comment]
# Telescope DNS Configure File
# https://github.com/wolf-joe/ts-dns

listen = ":5353"
gfwlist = "gfwlist.txt"
gfwlist_b64 = true
cnip = "cnip.txt"
disable_qtypes = ["AAAA", "HTTPS"]

[query_log]
file = "/dev/null"
ignore_qtypes = ["DNSKEY", "NS"]
ignore_cache = false
ignore_hosts = true

[cache]
size = 4096
min_ttl = 1
max_ttl = 86400

[groups]
[groups.clean]
ecs = "1.2.4.0/24"
no_cookie = false
dns = ["119.29.29.29", "123.125.81.6"]
concurrent = true

fastest_v4 = true
tcp_ping_port = 80
 
[groups.dirty]
dns = ["208.67.222.222:5353"]

ipset = "blocked"
ipset_ttl = 8640

**Comment by wolf-joe** [comment]
可以移除`[query_log]`里的`file = "/dev/null"`选项打印全部日志吗？另外运行时开启debug模式能打印更多日志方便分析（`./ts-dns -vv`）
不过确实`fastest_ipv4`这块写的比较粗糙，之后会慢慢重构😂

**Comment by hkthomas** [comment]
N=s1.url.cn. Q_TYPE=A SRC="127.0.0.1:8076"
DEBU[0010] forward question [{s1.url.cn. 1 1}] to &{0xc00016e070 123.125.81.6:53 <nil> 0xc0000875c0}  LOCATION="server.go:52" LOG_ID=24624 QUESTION=s1.url.cn. Q_TYPE=A SRC="127.0.0.1:8076"
INFO[0010] cn/empty ipv4                                 GROUP=clean LOCATION="server.go:192" LOG_ID=24624 QUESTION=s1.url.cn. Q_TYPE=A SRC="127.0.0.1:8076"
DEBU[0010] response: ["s1.url.cn.\t60\tIN\tCNAME\t111s1.url.cn.cloud.tc.qq.com." "111s1.url.cn.cloud.tc.qq.com.\t60\tIN\tCNAME\ts1.url.cn.tcdn.qq.com." "s1.url.cn.tcdn.qq.com.\t60\tIN\tCNAME\ts1.url.cn.sched.p2v6.tdnsv6.com." "s1.url.cn.sched.p2v6.tdnsv6.com.\t60\tIN\tA\t221.228.216.139"]  LOCATION="server.go:145" LOG_ID=24624 QUESTION=s1.url.cn. Q_TYPE=A SRC="127.0.0.1:8076"
INFO[0010] cn/empty ipv4                                 GROUP=clean LOCATION="server.go:192" LOG_ID=64108 QUESTION=s.url.cn. Q_TYPE=A SRC="127.0.0.1:33571"
DEBU[0010] response: ["s.url.cn.\t79\tIN\tCNAME\tqplus.tc.qq.com." "qplus.tc.qq.com.\t79\tIN\tCNAME\tssdv6mid.tcdn.qq.com." "ssdv6mid.tcdn.qq.com.\t79\tIN\tCNAME\tssdv6.tcdn.qq.com." "ssdv6.tcdn.qq.com.\t79\tIN\tA\t58.216.107.91"]  LOCATION="server.go:145" LOG_ID=64108 QUESTION=s.url.cn. Q_TYPE=A SRC="127.0.0.1:33571"
DEBU[0010] question: [{"web.qun.qq.com." '\x01' '\x01'}], extract: ["\n;; OPT PSEUDOSECTION:\n; EDNS: version 0; flags: do; udp: 4096\n; SUBNET: 58.210.143.0/24/0"]  LOCATION="server.go:155" LOG_ID=7714 QUESTION=web.qun.qq.com. Q_TYPE=A SRC="127.0.0.1:59465"
INFO[0010] match by rules                                GROUP=clean LOCATION="server.go:180" LOG_ID=7714 QUESTION=web.qun.qq.com. Q_TYPE=A SRC="127.0.0.1:59465"
DEBU[0010] forward question [{web.qun.qq.com. 1 1}] to &{0xc00016e000 119.29.29.29:53 <nil> 0xc000087560}  LOCATION="server.go:52" LOG_ID=7714 QUESTION=web.qun.qq.com. Q_TYPE=A SRC="127.0.0.1:59465"
DEBU[0010] forward question [{web.qun.qq.com. 1 1}] to &{0xc00016e070 123.125.81.6:53 <nil> 0xc0000875c0}  LOCATION="server.go:52" LOG_ID=7714 QUESTION=web.qun.qq.com. Q_TYPE=A SRC="127.0.0.1:59465"
DEBU[0010] response: ["web.qun.qq.com.\t258\tIN\tA\t101.89.15.141"]  LOCATION="server.go:145" LOG_ID=7714 QUESTION=web.qun.qq.com. Q_TYPE=A SRC="127.0.0.1:59465"
DEBU[0010] question: [{"go.microsoft.com." '\x01' '\x01'}], extract: ["\n;; OPT PSEUDOSECTION:\n; EDNS: version 0; flags: do; udp: 4096\n; SUBNET: 58.210.143.0/24/0"]  LOCATION="server.go:155" LOG_ID=24673 QUESTION=go.microsoft.com. Q_TYPE=A SRC="127.0.0.1:18686"
DEBU[0010] forward question [{go.microsoft.com. 1 1}] to &{0xc00016e000 119.29.29.29:53 <nil> 0xc000087560}  LOCATION="server.go:52" LOG_ID=24673 QUESTION=go.microsoft.com. Q_TYPE=A SRC="127.0.0.1:18686"
DEBU[0010] forward question [{go.microsoft.com. 1 1}] to &{0xc00016e070 123.125.81.6:53 <nil> 0xc0000875c0}  LOCATION="server.go:52" LOG_ID=24673 QUESTION=go.microsoft.com. Q_TYPE=A SRC="127.0.0.1:18686"
INFO[0011] not match gfwlist                             GROUP=clean LOCATION="server.go:195" LOG_ID=24673 QUESTION=go.microsoft.com. Q_TYPE=A SRC="127.0.0.1:18686"
DEBU[0011] response: ["go.microsoft.com.\t1\tIN\tCNAME\tgo.microsoft.com.edgekey.net." "go.microsoft.com.edgekey.net.\t1\tIN\tCNAME\te11290.dspg.akamaiedge.net." "e11290.dspg.akamaiedge.net.\t1\tIN\tA\t23.194.76.3"]  LOCATION="server.go:145" LOG_ID=24673 QUESTION=go.microsoft.com. Q_TYPE=A SRC="127.0.0.1:18686"
DEBU[0012] question: [{"stopservice.chshap.blob.core.windows.net." '\x01' '\x01'}], extract: ["\n;; OPT PSEUDOSECTION:\n; EDNS: version 0; flags: do; udp: 4096\n; SUBNET: 58.210.143.0/24/0"]  LOCATION="server.go:155" LOG_ID=1893 QUESTION=stopservice.chshap.blob.core.windows.net. Q_TYPE=A SRC="127.0.0.1:57418"
DEBU[0012] forward question [{stopservice.chshap.blob.core.windows.net. 1 1}] to &{0xc00016e000 119.29.29.29:53 <nil> 0xc000087560}  LOCATION="server.go:52" LOG_ID=1893 QUESTION=stopservice.chshap.blob.core.windows.net. Q_TYPE=A SRC="127.0.0.1:57418"
DEBU[0012] forward question [{stopservice.chshap.blob.core.windows.net. 1 1}] to &{0xc00016e070 123.125.81.6:53 <nil> 0xc0000875c0}  LOCATION="server.go:52" LOG_ID=1893 QUESTION=stopservice.chshap.blob.core.windows.net. Q_TYPE=A SRC="127.0.0.1:57418"
ERRO[0012] find fastest ipv4 failed
INFO[0012] cn/empty ipv4                                 GROUP=clean LOCATION="server.go:192" LOG_ID=1893 QUESTION=stopservice.chshap.blob.core.windows.net. Q_TYPE=A SRC="127.0.0.1:57418"
DEBU[0012] response: []                                  LOCATION="server.go:145" LOG_ID=1893 QUESTION=stopservice.chshap.blob.core.windows.net. Q_TYPE=A SRC="127.0.0.1:57418"

大概是这样，不过不存log文件截不全。

**Comment by hkthomas** [comment]
LOG_ID=10251 QUESTION=cambrian-images.cdn.bcebos.com. Q_TYPE=A SRC="127.0.0.1:5915"
DEBU[0300] forward question [{cambrian-images.cdn.bcebos.com. 1 1}] to &{0xc00016e070 123.125.81.6:53 <nil> 0xc0000875c0}  LOCATION="server.go:52" LOG_ID=10251 QUESTION=cambrian-images.cdn.bcebos.com. Q_TYPE=A SRC="127.0.0.1:5915"
INFO[0300] cn/empty ipv4                                 GROUP=clean LOCATION="server.go:192" LOG_ID=28930 QUESTION=vdposter.bdstatic.com. Q_TYPE=A SRC="127.0.0.1:49082"
DEBU[0300] response: ["vdposter.bdstatic.com.\t55\tIN\tCNAME\tvdposter.bdstatic.com.a.bdydns.com." "vdposter.bdstatic.com.a.bdydns.com.\t55\tIN\tCNAME\topencdnbdvdposter.jomodns.com." "opencdnbdvdposter.jomodns.com.\t55\tIN\tA\t114.80.30.35"]  LOCATION="server.go:145" LOG_ID=28930 QUESTION=vdposter.bdstatic.com. Q_TYPE=A SRC="127.0.0.1:49082"
DEBU[0300] response: ["gimg4.baidu.com.\t1\tIN\tCNAME\tgimg4.baidu.com.a.bdydns.com." "gimg4.baidu.com.a.bdydns.com.\t1\tIN\tCNAME\topencdnbdsimage.jomodns.com." "opencdnbdsimage.jomodns.com.\t1\tIN\tA\t180.97.66.36"]  LOCATION="server.go:145" LOG_ID=51405 QUESTION=gimg4.baidu.com. Q_TYPE=A SRC="127.0.0.1:5637"
INFO[0300] cn/empty ipv4                                 GROUP=clean LOCATION="server.go:192" LOG_ID=10251 QUESTION=cambrian-images.cdn.bcebos.com. Q_TYPE=A SRC="127.0.0.1:5915"
DEBU[0300] response: ["cambrian-images.cdn.bcebos.com.\t1\tIN\tCNAME\tcambrian-images.cdn.bcebos.com.a.bdydns.com." "cambrian-images.cdn.bcebos.com.a.bdydns.com.\t1\tIN\tCNAME\topencdnssl.jomodns.com." "opencdnssl.jomodns.com.\t1\tIN\tA\t117.91.181.35"]  LOCATION="server.go:145" LOG_ID=10251 QUESTION=cambrian-images.cdn.bcebos.com. Q_TYPE=A SRC="127.0.0.1:5915"
ERRO[0300] find fastest ipv4 failed
DEBU[0300] response: ["dss1.baidu.com.\t60\tIN\tCNAME\tsslbaiduv6.jomodns.com." "sslbaiduv6.jomodns.com.\t60\tIN\tA\t121.227.7.33"]  LOCATION="server.go:145" LOG_ID=65248 QUESTION=dss1.baidu.com. Q_TYPE=A SRC="127.0.0.1:26403"
ERRO[0300] find fastest ipv4 failed
DEBU[0300] response: ["dss2.baidu.com.\t60\tIN\tCNAME\tsslbaiduv6.jomodns.com." "sslbaiduv6.jomodns.com.\t60\tIN\tA\t121.227.7.33"]  LOCATION="server.go:145" LOG_ID=46687 QUESTION=dss2.baidu.com. Q_TYPE=A SRC="127.0.0.1:17119"
DEBU[0316] question: [{"login.live.com." '\x01' '\x01'}], extract: ["\n;; OPT PSEUDOSECTION:\n; EDNS: version 0; flags: do; udp: 4096\n; SUBNET: 58.210.143.0/24/0"]  LOCATION="server.go:155" LOG_ID=47656 QUESTION=login.live.com. Q_TYPE=A SRC="127.0.0.1:24751"
DEBU[0316] forward question [{login.live.com. 1 1}] to &{0xc00016e000 119.29.29.29:53 <nil> 0xc000087560}  LOCATION="server.go:52" LOG_ID=47656 QUESTION=login.live.com. Q_TYPE=A SRC="127.0.0.1:24751"
DEBU[0316] forward question [{login.live.com. 1 1}] to &{0xc00016e070 123.125.81.6:53 <nil> 0xc0000875c0}  LOCATION="server.go:52" LOG_ID=47656 QUESTION=login.live.com. Q_TYPE=A SRC="127.0.0.1:24751"
INFO[0316] not match gfwlist                             GROUP=clean LOCATION="server.go:195" LOG_ID=47656 QUESTION=login.live.com. Q_TYPE=A SRC="127.0.0.1:24751"
DEBU[0316] response: ["login.live.com.\t1\tIN\tCNAME\tlogin.msa.msidentity.com." "login.msa.msidentity.com.\t1\tIN\tCNAME\twww.tm.lg.prod.aadmsa.trafficmanager.net." "www.tm.lg.prod.aadmsa.trafficmanager.net.\t1\tIN\tCNAME\tprda.aadg.msidentity.com." "prda.aadg.msidentity.com.\t1\tIN\tCNAME\twww.tm.a.prd.aadg.trafficmanager.net." "www.tm.a.prd.aadg.trafficmanager.net.\t1\tIN\tA\t40.126.52.146"]  LOCATION="server.go:145" LOG_ID=47656 QUESTION=login.live.com. Q_TYPE=A SRC="127.0.0.1:24751"
DEBU[0321] question: [{"ecs.office.com." '\x01' '\x01'}], extract: ["\n;; OPT PSEUDOSECTION:\n; EDNS: version 0; flags: do; udp: 4096\n; SUBNET: 58.210.143.0/24/0"]  LOCATION="server.go:155" LOG_ID=3643 QUESTION=ecs.office.com. Q_TYPE=A SRC="127.0.0.1:58621"
DEBU[0321] forward question [{ecs.office.com. 1 1}] to &{0xc00016e000 119.29.29.29:53 <nil> 0xc000087560}  LOCATION="server.go:52" LOG_ID=3643 QUESTION=ecs.office.com. Q_TYPE=A SRC="127.0.0.1:58621"
DEBU[0321] forward question [{ecs.office.com. 1 1}] to &{0xc00016e070 123.125.81.6:53 <nil> 0xc0000875c0}  LOCATION="server.go:52" LOG_ID=3643 QUESTION=ecs.office.com. Q_TYPE=A SRC="127.0.0.1:58621"
INFO[0321] not match gfwlist                             GROUP=clean LOCATION="server.go:195" LOG_ID=3643 QUESTION=ecs.office.com. Q_TYPE=A SRC="127.0.0.1:58621"
DEBU[0321] response: ["ecs.office.com.\t30\tIN\tCNAME\tecs.office.trafficmanager.net." "ecs.office.trafficmanager.net.\t30\tIN\tCNAME\ts-0005-office.config.skype.com." "s-0005-office.config.skype.com.\t30\tIN\tCNAME\tecs-office.s-0005.s-msedge.net." "ecs-office.s-0005.s-msedge.net.\t30\tIN\tCNAME\ts-0005.s-msedge.net." "s-0005.s-msedge.net.\t30\tIN\tA\t52.113.194.132"]  LOCATION="server.go:145" LOG_ID=3643 QUESTION=ecs.office.com. Q_TYPE=A SRC="127.0.0.1:58621"

**Comment by wolf-joe** [comment]
从日志来看，应该是ts-dns没能从上游DNS响应中获取到可以用来测速的ipv4地址导致报错。这个并不影响解析，也属于正常范围，可以忽略，争取下个版本将这块优化一下

**Comment by hkthomas** [comment]
好的，我以为是获取最快IP失败然后随机返回了一个IP呢。
