### ISSUE TITLE
DoH 格式更改？

### ISSUE THREAD

**Issue by rampageX** [wolf-joe/ts-dns#4]
0.8.2 修改了 DoH 格式，我看了下配置文件： 

如果 `1.0.0.1:443@cloudflare-dns.com` 对应 `https://cloudflare-dns.com/dns-query` ，那么类似 `https://commons.host`, `https://doh.dnswarden.com/adblock` 该怎么写？之前的格式并没有任何问题啊，我看过所有的支持 DoH 的客户端都是维持 https 开头那个格式嘛。

请参考： https://github.com/curl/curl/wiki/DNS-over-HTTPS

**Comment by wolf-joe** [comment]
抱歉，是我先入为主了，误以为RFC 8484限定了path。release已撤回。
