### ISSUE TITLE
Log to file

### ISSUE THREAD

**Issue by daiooo** [wolf-joe/ts-dns#6]
Like:

Log to file:

$ ./ts-dns -l /path/to/log.log

**Comment by wolf-joe** [comment]
query log can log to file now(see [ts-dns-full.toml](https://github.com/wolf-joe/ts-dns/blob/master/ts-dns-full.toml#L14)).
in my opinion, "log to file" is a part of daemon feature, so i recommend to use third part daemon tool (like [supervisor](http://supervisord.org/introduction.html)) before ts-dns support it.

**Comment by wolf-joe** [comment]
已在wiki中加入[配置systemd的文章](https://github.com/wolf-joe/ts-dns/wiki/%E9%85%8D%E7%BD%AEsystemd)，有兴趣的可以看下。
