### ISSUE TITLE
dns请求超时

### ISSUE THREAD

**Issue by weargle** [wolf-joe/ts-dns#7]
请教下，不知道为什么偶尔会出现设置的dns出现请求超时情况，错误格式query dns error: read udp 172.20.250.225:53190->xxx.xxx.xxx.xx:5353: i/o timeout，想问下这是什么情况造成的。反馈一下最新版出现query dns error: dns: buffer size too small 这个错误，缓存大小设置的是你提供的全面配置文件里的值，在0.9.1版本没有这种情况

**Comment by wolf-joe** [comment]
`read udp ... i/o timeout`就是字面意义上的超时：`ts-dns`转发dns请求时，远程dns服务器的响应时间超过了2秒的默认值。
`query dns error: dns: buffer size too small`这个报错我没有遇到过，能提供下对应配置文件和日志前后部分吗？

**Comment by weargle** [comment]
配置文件如下：
# Telescope DNS Configure File
# https://github.com/wolf-joe/ts-dns

listen = ":53"
gfwlist = "gfwlist.txt"
cnip = "cnip.txt"
disable_ipv6 = true # 禁用IPv6地址解析

hosts_files = ["hosts.txt", "adaway.txt", "yhosts.txt", "dasheng.txt", "1024Hosts.txt", "neoHosts.txt", "Hblock.txt", "black.txt", "yousList.txt"]  # hosts文件路径，支持多hosts
[hosts] # 自定义域名映射
"cloudflare-dns.com" = "1.0.0.1"
"dns.google" = "8.8.8.8"

[cache]  # dns缓存配置
size = 4096  # 缓存大小，为负数时禁用缓存
min_ttl = 60  # 最小ttl，单位为秒
max_ttl = 86400  # 最大ttl，单位为秒

[groups]
  [groups.clean]
  dns = ["119.29.29.29", "223.6.6.6", "114.114.114.114"]
  #fastest_v4 = true  # 选择ping值最低的ipv4地址作为响应，启用时建议以root权限允许本程序
  concurrent = true

  [groups.dirty]
  dns = [ "208.67.222.222:5353", "176.103.130.130:5353"]
  dot = ["1.0.0.1:853@cloudflare-dns.com"]  # dns over tls服务器
  doh = ["https://cloudflare-dns.com/dns-query", "https://dns.google/dns-query"]  # dns over https服务器
  
  ipset = "blocked"  # 目标IPSet名称，该组所有域名的ipv4解析结果将加入到该IPSet中
  ipset_ttl = 86400 # ipset记录超时时间，单位为秒，推荐设置以避免ipset记录过多

dns日志已经没有了，没办法提供，但是我只能说跟正常解析的日志一样，只是突然出现

**Comment by weargle** [comment]
非常抱歉，我弄错了一件事，在0.9.1版本也出现这个问题，这是我刚翻了日志看到的（我刚记起我记录了日志），
![image](https://user-images.githubusercontent.com/26951765/78549414-ec851a80-7834-11ea-93f3-7596e00600fd.png)

**Comment by weargle** [comment]
建议增加设置超时时间，解决有些dns回复慢就会导致超时情况

**Comment by wolf-joe** [comment]
> 建议增加设置超时时间，解决有些dns回复慢就会导致超时情况

2s的延迟在绝大部分情况下已经够用了，一个dns服务器如果2秒还没有答复一般认为数据包已经丢失。
单个group配置多个上游dns，如开启并发请求（`concurrent`为`true`），那这种超时可以忽略（除非所有的上游dns都超时了）；如未开启并发请求，ts-dns采用的是故障转移策略，第一个dns超时则用第二个dns再次请求，顺序是`dns`->`dot`->`doh`。

**Comment by wolf-joe** [comment]
> 非常抱歉，我弄错了一件事，在0.9.1版本也出现这个问题，日志如下
> ![image](https://user-images.githubusercontent.com/26951765/78549414-ec851a80-7834-11ea-93f3-7596e00600fd.png)

我在我的pc上启动了v0.9.1，用`[ "208.67.222.222:5353", "176.103.130.130:5353"]`作为`dirty`组的dns上游，然后请求`android.clients.google.com`，没有复现日志中出现的bug。

日志中对`android.clients.google.com`的提示是`match gfwlist`，也就是说该域名已经向`clean`组dns上游请求过一次且正常返回了结果，所以不太可能是ts-dns本身的问题。考虑到udp数据包本身有被篡改或抢答的可能性，所以我建议还是尽可能优先使用安全性更高的dot和doh作为`dirty`组的上游dns。

**Comment by weargle** [comment]
> > 非常抱歉，我弄错了一件事，在0.9.1版本也出现这个问题，日志如下
> > ![图片](https://user-images.githubusercontent.com/26951765/78549414-ec851a80-7834-11ea-93f3-7596e00600fd.png)
> 
> 我在我的pc上启动了v0.9.1，用`[ "208.67.222.222:5353", "176.103.130.130:5353"]`作为`dirty`组的dns上游，然后请求`android.clients.google.com`，没有出现。
> 
> 日志中对`android.clients.google.com`的提示是`match gfwlist`，与此该域名已经向`clean`组dns上游请求过一次且正常返回了结果，所以不太可能是ts-dns本身的问题。考虑到udp数据包本身有被篡改或抢答的可能，所以我建议还是优先使用安全性更高的点和doh作为`dirty`组的上游dns。

使用这个地址android.clients.google.com，我试了一下0.10版本这个地址会报这个错误

**Comment by wolf-joe** [comment]
> > > 非常抱歉，我弄错了一件事，在0.9.1版本也出现这个问题，日志如下
> > > ![图片](https://user-images.githubusercontent.com/26951765/78549414-ec851a80-7834-11ea-93f3-7596e00600fd.png)
> > 
> > 
> > 我在我的pc上启动了v0.9.1，用`[ "208.67.222.222:5353", "176.103.130.130:5353"]`作为`dirty`组的dns上游，然后请求`android.clients.google.com`，没有出现。
> > 日志中对`android.clients.google.com`的提示是`match gfwlist`，与此该域名已经向`clean`组dns上游请求过一次且正常返回了结果，所以不太可能是ts-dns本身的问题。考虑到udp数据包本身有被篡改或抢答的可能，所以我建议还是优先使用安全性更高的点和doh作为`dirty`组的上游dns。
> 
> 使用这个地址android.clients.google.com，我试了一下0.10版本这个地址会报这个错误

抱歉，我用v0.10.0也无法复现

**Comment by weargle** [comment]
> > > > 非常抱歉，我弄错了一件事，在0.9.1版本也出现这个问题，日志如下
> > > > ![图片](https://user-images.githubusercontent.com/26951765/78549414-ec851a80-7834-11ea-93f3-7596e00600fd.png)
> > > 
> > > 
> > > 我在我的pc上启动了v0.9.1，用`[ "208.67.222.222:5353", "176.103.130.130:5353"]`作为`dirty`组的dns上游，然后请求`android.clients.google.com`，没有出现。
> > > 日志中对`android.clients.google.com`的提示是`match gfwlist`，与此该域名已经向`clean`组dns上游请求过一次且正常返回了结果，所以不太可能是ts-dns本身的问题。考虑到udp数据包本身有被篡改或抢答的可能，所以我建议还是优先使用安全性更高的点和doh作为`dirty`组的上游dns。
> > 
> > 
> > 使用这个地址android.clients.google.com，我试了一下0.10版本这个地址会报这个错误
> 
> 抱歉，我用v0.10.0也无法复现

我用这个域名复现的结果，我发现这个域名有概率在重启dns时候后出现。
![image](https://user-images.githubusercontent.com/26951765/78557806-0da13780-7844-11ea-83d8-bd9eaec023f5.png)

**Comment by wolf-joe** [comment]
试试用其它的dns上游呢？比如在配置文件里注释掉dns那一行，只配置dot和doh，或使用安全的socks5代理？

**Comment by weargle** [comment]
> 试试用其它的dns上游呢？比如在配置文件里注释掉dns那一行，只配置dot和doh，或使用安全的socks5代理？

如果把最后的dns注释会带来这个后果。
![image](https://user-images.githubusercontent.com/26951765/78568341-8d370280-7854-11ea-9f52-8c999641b714.png)

**Comment by wolf-joe** [comment]
> > 试试用其它的dns上游呢？比如在配置文件里注释掉dns那一行，只配置dot和doh，或使用安全的socks5代理？
> 
> 如果把最后的dns注释会带来这个后果，socks5代理我没有。
> ![image](https://user-images.githubusercontent.com/26951765/78568341-8d370280-7854-11ea-9f52-8c999641b714.png)

如果说dot或doh能正常解析之前出问题的域名的话，那最合理的解释应该就是普通udp/tcp dns服务器的响应被篡改了……

**Comment by weargle** [comment]
可能吧，这个帖子就到这里吧，作者没有办法复现是没有办法解决

**Comment by wolf-joe** [comment]
底层DNS库相关的issue可以参考[miekg/dns#214](https://github.com/miekg/dns/issues/214)、[miekg/dns#439](https://github.com/miekg/dns/issues/439)
